shared: &shared
    - "packages/superspider-shared/**"
    - "package.json"
    - "pnpm-lock.yaml"
    - "pnpm-workspace.yaml"
    - "tsconfig.json"
mcore:
    - *shared
    - "packages/superspider-mcore/**"
mdb:
    - *shared
    - "packages/superspider-mdb/**"
predb:
    - *shared
    - "packages/superspider-predb/**"
showcase:
    - *shared
    - "packages/superspider-showcase/**"
