version: "3.7"
services:
    superspider-mongo:
        image: mongo
        container_name: superspider-mongo
        restart: unless-stopped
        volumes:
            - mongodata:/data/db
        networks:
            - default
        environment:
            NODE_ENV: production
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
    superspider-predb:
        build:
            context: .
            dockerfile: ./packages/superspider-predb/Dockerfile
        container_name: superspider-predb
        restart: unless-stopped
        depends_on:
            - superspider-mongo
        networks:
            - default
        environment:
            NODE_ENV: production
            MONGODB_PASS: admin
            MONGODB_IP: superspider-mongo
    superspider-mdb:
        build:
            context: .
            dockerfile: ./packages/superspider-mdb/Dockerfile
        container_name: superspider-mdb
        restart: unless-stopped
        depends_on:
            - superspider-mongo
        networks:
            - default
        environment:
            MONGODB_PASS: admin
            MONGODB_IP: superspider-mongo
    superspider-mcore:
        build:
            context: .
            dockerfile: ./packages/superspider-mcore/Dockerfile
        container_name: superspider-mcore
        restart: unless-stopped
        depends_on:
            - superspider-mongo
            - superspider-mdb
        environment:
            MONGODB_PASS: admin
            MONGODB_IP: superspider-mongo
        ports:
            - "2162:2162"
        networks:
            - default
    superspider-showcase:
        build:
            context: .
            dockerfile: ./packages/superspider-showcase/Dockerfile
        container_name: superspider-showcase
        environment:
            BASE_API_URL: https://api.example.com
        ports:
            - "2164:2164"
        networks:
            - default

volumes:
    mongodata:


networks:
    default:
        driver: bridge
