version: "3.7"
services:
  mongo:
    image: mongo
    restart: unless-stopped
    container_name: mongo
    volumes:
      - mongodata:/data/db
      - ./backup:/backup
    networks:
      - default
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: superspider
  superspider-predb:
    build: ./packages/superspider-predb
    container_name: superspider-predb
    depends_on:
      - mongo
    networks:
      - default
    environment:
      MONGODB_PASS: superspider
      MONGODB_IP: mongo
  superspider-mdb:
    build: ./packages/superspider-mdb
    container_name: superspider-mdb
    depends_on:
      - mongo
    networks:
      - default
    environment:
      MONGODB_PASS: superspider
      MONGODB_IP: mongo
  superspider-mcore:
    build: ./packages/superspider-mcore
    container_name: superspider-mcore
    depends_on:
      - mongo
      - superspider-mdb
    environment:
      MONGODB_PASS: superspider
      MONGODB_IP: mongo
    ports:
      - "2162:2162"
    networks:
      - default
      - sharenet
  superspider-showcase:
    build: ./packages/superspider-showcase
    container_name: superspider-showcase
    environment:
      BASE_API_URL: https://bilisc.api.acedroidx.top:4430
    ports:
      - "2164:2164"
    networks:
      - default
      - sharenet

volumes:
  mongodata:

networks:
  default:
    driver: bridge
  sharenet:
    external: true
