name: "SuperSpider Docker Build"

on:
    push:
        branches:
            - master
            - dev
    workflow_dispatch:

jobs:
    changes:
        runs-on: ubuntu-latest
        outputs:
            packages: ${{ steps.filter.outputs.changes }}
        steps:
            - uses: actions/checkout@v4
            - uses: dorny/paths-filter@v3
              id: filter
              with:
                  base: ${{ github.ref }}
                  filters: .github/path-filters.yml
    build-docker:
        needs: [changes]
        if: always() && needs.changes.outputs.packages != '[]'
        strategy:
            matrix:
                package: ${{ fromJSON(needs.changes.outputs.packages) }}
                exclude:
                    - package: shared
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Branch name
              run: echo running on branch ${GITHUB_REF##*/}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: acedroidx/superspider-${{ matrix.package }}
            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./packages/superspider-${{ matrix.package }}/Dockerfile
                  build-args: |
                      IMAGE_TAG=${{ github.ref_name }}
                      GIT_HASH=${{ github.sha }}
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                #   cache-from: type=registry,ref=acedroidx/superspider-${{ matrix.package }}:buildcache
                #   cache-to: type=registry,ref=acedroidx/superspider-${{ matrix.package }}:buildcache,mode=max
