name: "SuperSpider Mdb Build"

on:
  push:
    branches:
      - master
      - dev
    paths:
      - "packages/superspider-mdb/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - "tsconfig.json"
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Build
        run: docker build -f ./packages/superspider-mdb/Dockerfile -t acedroidx/superspider-mdb:${GITHUB_REF##*/} .
      - name: Log In
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push
        run: docker push acedroidx/superspider-mdb:${GITHUB_REF##*/}
